# Generated by Django 3.2.16 on 2022-11-12 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=200)),
                ('debt', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_model', models.CharField(max_length=100)),
                ('product_launch_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('factory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='net.factory')),
            ],
            bases=('net.factory',),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('factory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='net.factory')),
            ],
            bases=('net.factory',),
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('factory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='net.factory')),
            ],
            bases=('net.factory',),
        ),
        migrations.CreateModel(
            name='LargeRetailChain',
            fields=[
                ('factory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='net.factory')),
            ],
            bases=('net.factory',),
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='net.net')),
            ],
        ),
        migrations.AddField(
            model_name='factory',
            name='net_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='net.net'),
        ),
        migrations.AddField(
            model_name='factory',
            name='products',
            field=models.ManyToManyField(to='net.Product'),
        ),
    ]
